{
 "title": "eShop Ordering Metrics Dashboard",
 "tags": [
  "eshop",
  "orders",
  "metrics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Order Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Orders",
   "type": "stat",
   "description": "Total number of orders placed",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mk_order_placed_count_total)"
    }
   ]
  },
  {
   "title": "Order Rate",
   "type": "timeseries",
   "description": "Order placement rate",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "orders/min" } },
   "targets": [
    {
     "expr": "sum(rate(mk_order_placed_count_total[5m])) * 60",
     "legendFormat": "Orders per minute"
    }
   ]
  },
  { "title": "Revenue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Revenue",
   "type": "stat",
   "description": "Total revenue from all orders",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mk_revenue_USD_total)" }
   ]
  },
  {
   "title": "Revenue Growth",
   "type": "timeseries",
   "description": "Revenue over time",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sum(mk_revenue_USD_total)", "legendFormat": "Revenue Rate" }
   ]
  },
  { "title": "Order Value Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Top 5 Order Value per User",
   "type": "piechart",
   "description": "Top 5 Order Value per User",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (userId) (mk_order_value_USD_sum/2))",
     "legendFormat": "{{le}} USD"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "timeseries",
   "description": "Average order value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "(sum(mk_order_value_USD_sum) / sum(mk_order_placed_count_total)) / 2\n",
     "legendFormat": "Average Order Value"
    }
   ]
  },
  { "title": "User Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Top 10 Users by Order Count",
   "type": "bargauge",
   "description": "Orders placed by each user",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, mk_orders_by_user_total{userName!=\"\"})",
     "legendFormat": "{{userName}}"
    }
   ]
  },
  { "title": "Business Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Current Average Order Value",
   "type": "stat",
   "description": "Average order value over time",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mk_revenue_USD_total) / sum(mk_order_placed_count_total)"
    }
   ]
  },
  {
   "title": "Average Revenue per User",
   "type": "stat",
   "description": "Average revenue per user",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mk_revenue_USD_total) / count(mk_order_placed_count_total)\n\n"
    }
   ]
  },
  {
   "title": "Pending Payment",
   "type": "gauge",
   "description": "Orders yet to be processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(active_orders)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order Rate vs Route Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mk_order_placed_count_total[5m])",
     "legendFormat": "Orders Rate"
    },
    {
     "expr": "rate(aspnetcore_routing_match_attempts_total[5m])",
     "legendFormat": "Route Requests"
    }
   ]
  }
 ]
}